# Use a base image with Node.js
FROM node:14-slim

# Set the working directory
WORKDIR /usr/src/app

# Copy only the package.json and package-lock.json files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Specify the default command to run your app
CMD [ "npm", "run", "dev" ]
